package UI;

import javax.swing.JFrame;

import UI.worldsIMPL.WorldOfDodge;

import static utils.Constantes.*;

import java.awt.Component;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;


public class Application extends JFrame{

	private static final long serialVersionUID = -6106657621450573292L;
	private World world;
	
	public Application()
	{
		super(TITRE_APPLICATION);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */


	private void initComponents() {

		worldPanel = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		generateWorldButton = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		stopWorldButton = new javax.swing.JButton();
		returnHomePositionButton = new javax.swing.JButton();

		worldPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		javax.swing.GroupLayout worldPanelLayout = new javax.swing.GroupLayout(worldPanel);
		worldPanel.setLayout(worldPanelLayout);
		worldPanelLayout.setHorizontalGroup(
				worldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				);
		worldPanelLayout.setVerticalGroup(
				worldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel2.setText("World");

		generateWorldButton.setText("Valider");
		generateWorldButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
					generateWorldButtonActionPerformed(evt);
			}
		});

		stopWorldButton.setText("Arrêter simulation");
		stopWorldButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				stopWorldSimulationActionperformed(evt);
			}
		});
		stopWorldButton.setEnabled(false);
		
		returnHomePositionButton.setText("Retour à la position de départ");
		returnHomePositionButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				returnHomePositionActionperformed(evt);
			}
		});
		returnHomePositionButton.setEnabled(false);

		jLabel4.setText("Taille");

		jTextField2.setText("120");

		jTextField3.setText("120");

		jLabel5.setText("x");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jLabel2)
						.addGap(0, 0, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(generateWorldButton)
						.addContainerGap())
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel5)
										.addGap(2, 2, 2)
										.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(349, 349, 349))
								.addGroup(jPanel1Layout.createSequentialGroup()
										.addComponent(jLabel4)
										.addGap(386, 386, 386))))
				);
		jPanel1Layout.setVerticalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jLabel2)
						.addGap(36, 36, 36)
						.addComponent(jLabel4)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel5))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
						.addComponent(generateWorldButton)
						.addContainerGap())
				);


		jScrollPane1.setViewportView(worldPanel);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(stopWorldButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(returnHomePositionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
						.addContainerGap())
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGap(0, 50, Short.MAX_VALUE)
										.addComponent(stopWorldButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGap(0, 20, Short.MAX_VALUE)
										.addComponent(returnHomePositionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGap(0, 600, Short.MAX_VALUE)))
						.addContainerGap())
				);

		pack();
	}


	private void generateWorldButtonActionPerformed(java.awt.event.ActionEvent evt) {      
		int x=Integer.parseInt(jTextField2.getText());
		int y=Integer.parseInt(jTextField3.getText());
		//this.world=new WorldBeesWasps();
		//this.world=new WorldOfTanks();
		this.world = new WorldOfDodge();
		worldPanel.add(world);
		worldPanel.repaint();
		world.start(x, y);
		for (Component c : jPanel1.getComponents())
			c.setEnabled(false);
		stopWorldButton.setEnabled(true);
		returnHomePositionButton.setEnabled(true);
		world.grabFocus();
	}        

	private void stopWorldSimulationActionperformed(ActionEvent evt)
	{
		this.world=null;
		worldPanel.removeAll();
		for (Component c : jPanel1.getComponents())
			c.setEnabled(true);
		stopWorldButton.setEnabled(false);
		returnHomePositionButton.setEnabled(false);
	}
	
	private void returnHomePositionActionperformed(ActionEvent evt)
	{
		SCROLL_X=0;
		SCROLL_Y=0;
	}

	/**
	 * @param args the command line arguments
	 */

	// Variables declaration - do not modify                     
	private javax.swing.JButton generateWorldButton;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JPanel worldPanel;
	private javax.swing.JButton stopWorldButton;
	private javax.swing.JButton returnHomePositionButton;
	// End of variables declaration                   

	public static void main(String[] args)
	{
		EventQueue.invokeLater(new Runnable()
		{
			
			@Override
			public void run()
			{
				new Application().setVisible(true);
			}
		});
	}

}
